//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicsShop.AppData
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Korzina = new HashSet<Korzina>();
            this.OrdersPodr = new HashSet<OrdersPodr>();
            this.Sale = new HashSet<Sale>();
        }

        public int ID_Product { get; set; }
        public string Name { get; set; }
        public string Descript { get; set; }
        public decimal Price { get; set; }
        public int ID_Category { get; set; }
        public int ID_Brand { get; set; }
        public string Image { get; set; }
        public int StockQ { get; set; }
        public int ID_Country { get; set; }

        public virtual Brands Brands { get; set; }
        public virtual Category Category { get; set; }
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Korzina> Korzina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersPodr> OrdersPodr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sale { get; set; }


        public string CurrentPhoto
        {
            get
            {
                if (String.IsNullOrEmpty(Image) || String.IsNullOrEmpty(Image))
                {
                    return "/Images/picture.jpg";
                }

                else
                {
                    return "/Images/" + Image;
                }
            }
        }

    }
}